#!/bin/bash

mkdir /maze/maze_1 -p
sshfs -o nonempty -o password_stdin pi@192.168.137.100:/home/pi/maze_pi /maze/maze_1 <<< 'raspberry'
mkdir /maze/maze_2 -p
sshfs -o nonempty -o password_stdin pi@192.168.137.200:/home/pi/maze_pi /maze/maze_2 <<< 'raspberry'
